### ISSUE TITLE
first build fails, second succeeds

### ISSUE THREAD

**Issue by berndpfrommer** [versatran01/apriltag#1]
When using catkin build I get the below error on first compile. When I compile again it finishes without error.

Removing the _gencfg and _gencpp targets from CMakeLists.txt in apriltag_ros fixes the problem. I'm not familiar with the ROS build environment. Why the lines are there in the first place? Copied from legacy code?

add_dependencies(${PROJECT_NAME}
    ${catkin_EXPORTED_TARGETS}
    ${PROJECT_NAME}_gencfg
    ${PROJECT_NAME}_gencpp
    ${${PROJECT_NAME}_EXPORTED_TARGETS}
    )

_______________________________________________________________________________________________________
Errors     << apriltag_ros:cmake /home/bird/Documents/bird/logs/apriltag_ros/build.cmake.000.log       
CMake Error at /home/bird/Documents/bird/src/apriltag/apriltag_ros/CMakeLists.txt:38 (add_dependencies):
  The dependency target "apriltag_ros_gencpp" of target "apriltag_ros" does
  not exist.

**Comment by versatran01** [comment]
They are there to make sure apriltag_msgs are built before apriltag_ros I believe. Let me take a look.

**Comment by versatran01** [comment]
Yeah you were right, they were legacy code. Fixed in master now.
