### ISSUE TITLE
inconsistent meta package name for package.xml and CMakeLists.txt

### ISSUE THREAD

**Issue by berndpfrommer** [versatran01/apriltag#15]
apriltag doesn't compile under Ubuntu 20.04 / ROS Noetic:

```
Errors     << apriltag_meta:check /home/pfrommer/Documents/tagslam_root/logs/apriltag_meta/build.check.003.log                                                                                                    
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_package_xml.cmake:54 (message):
  catkin_package_xml() package name 'apriltag_meta' in
  '/home/pfrommer/Documents/tagslam_root/src/apriltag/apriltag/package.xml'
  does not match current PROJECT_NAME 'apriltag'.  You must call project()
  with the same package name before.
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_metapackage.cmake:39 (catkin_package_xml)
  CMakeLists.txt:5 (catkin_metapackage)
```

This is because of inconsistent package naming in the meta package, which is called "apriltag" in the CMakeLists.txt, and "apriltag_meta" in package.xml:

https://github.com/versatran01/apriltag/blob/master/apriltag/package.xml
https://github.com/versatran01/apriltag/blob/master/apriltag/CMakeLists.txt

Somehow this didn't trigger an error under Bionic/Melodic so I didn't catch it.

I actually introduced this bug when I renamed the package to apriltag_meta (just in package.xml) to avoid collision with the package naming in the umich apriltag detector, which happens to also be called "apriltag"

https://github.com/AprilRobotics/apriltag/blob/ab144219059da7f808364311b0b48e9440f34291/CMakeLists.txt

Two options to fix this:
1) for the umich apriltag repo and rename their package to apriltag_umich
2) rename the apriltag meta package to apriltag_meta (consistently in CMakeLists.txt and package.xml)

I think option 2) is the better one, although it may break some packages that are referencing "apriltag" now, and will need to be referencing "apriltag_meta" going forward. The problem with option 1) is that if people are already using the original umich apriltag repo in their workspace for another reason, they still will have a name collision.

**Comment by versatran01** [comment]
I don't think we need a meta pacakge? maybe just remove it.
