### ISSUE TITLE
Improving readme

### ISSUE THREAD

**Issue by MedericFourmy** [versatran01/apriltag#9]
Hello, thanks for this work.
I think the names of the launchfiles in the README are wrong 
`roslaunch apriltag_ros apriltag_detector_node.launch camera:=camera`
should be 
`roslaunch apriltag_ros detector.launch camera:=camera`

Also in this launchfile, I find it misleading to have a default border size of 2 since the easy to find [pdf from mit](https://robot2016.mit.edu/sites/default/files/documents/project_apriltag36h11.pdf) only includes sizes of 1.

**Comment by versatran01** [comment]
Thanks for the feedback. I'm currently refactoring this repo. The mit package will be removed as it is no longer supported. The only remaining one will be apriltag3. And I will also add some functionality to generate calibration grid and other stuff.
